---
engines:
  duplication:
    enabled: true
    checks:
      Identical code:
        enabled: false
      Similar code:
        enabled: false
      comma-dangle:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: test/fixtures/config/.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- docs/
- test/
- bin/
- scripts/
- lib/
